/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

/**
 *
 * @author ASUS
 */
public class managerSelect extends javax.swing.JFrame {

    /**
     * Creates new form managerSelect
     */
    public managerSelect() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        maCaAcc = new javax.swing.JButton();
        prDetails = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        maCaAcc.setBackground(new java.awt.Color(255, 204, 204));
        maCaAcc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        maCaAcc.setForeground(new java.awt.Color(0, 0, 0));
        maCaAcc.setText("Manage Cashier  Accounts");
        maCaAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maCaAccActionPerformed(evt);
            }
        });
        getContentPane().add(maCaAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 260, 40));

        prDetails.setBackground(new java.awt.Color(255, 204, 204));
        prDetails.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        prDetails.setForeground(new java.awt.Color(0, 0, 0));
        prDetails.setText("Product Details");
        prDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prDetailsActionPerformed(evt);
            }
        });
        getContentPane().add(prDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 260, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Desktop\\Projects\\ThePawsShop\\src\\images\\managerOptions.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 340));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void prDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prDetailsActionPerformed
      
        productManage prManage = new productManage();
        prManage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_prDetailsActionPerformed

    private void maCaAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maCaAccActionPerformed
        //cashir manage button work
        cashierManage caMannage = new cashierManage();  
        caMannage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_maCaAccActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(managerSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(managerSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(managerSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(managerSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new managerSelect().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton maCaAcc;
    private javax.swing.JButton prDetails;
    // End of variables declaration//GEN-END:variables
}
