/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

/**
 *
 * @author ASUS
 */
public class start extends javax.swing.JFrame {

    /**
     * Creates new form start
     */
    public start() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mabtn = new javax.swing.JButton();
        cabtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mabtn.setBackground(new java.awt.Color(102, 102, 102));
        mabtn.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        mabtn.setForeground(new java.awt.Color(0, 0, 0));
        mabtn.setText("Manager");
        mabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mabtnActionPerformed(evt);
            }
        });
        getContentPane().add(mabtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 150, 50));

        cabtn.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        cabtn.setForeground(new java.awt.Color(0, 0, 0));
        cabtn.setText("Cashier");
        cabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cabtnActionPerformed(evt);
            }
        });
        getContentPane().add(cabtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 150, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Desktop\\Projects\\ThePawsShop\\src\\images\\background.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 460));

        setSize(new java.awt.Dimension(757, 466));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mabtnActionPerformed
           managerLogin managerBtn = new managerLogin();
           managerBtn.setVisible(true);
           this.dispose();
    }//GEN-LAST:event_mabtnActionPerformed

    private void cabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cabtnActionPerformed
           cacashierLogin cashierBtn = new cacashierLogin();
           cashierBtn.setVisible(true);
           this.dispose();
    }//GEN-LAST:event_cabtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new start().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cabtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton mabtn;
    // End of variables declaration//GEN-END:variables
}
